### PR TITLE
Fix messages deleted by the client

### PR DESCRIPTION
**Pull request by Angelix1**
EEEEE

### CODE REVIEW

**Comment by Angelix1** [comment]
HEWLP

**Review by meqativ — CHANGES_REQUESTED** [review]
be more serious in code pls </img>
and you also deleted features which isn't good, please put them back in

**Comment by Angelix1** [comment]
> be more serious in code pls  and you also deleted features which isn't good, please put them back in

serious like? proper comments?
and i'll readd the feature, not right now doe, im kinda busy atm

**Comment by meqativ** [comment]
[`Vendetta › #plugins › #NoDelete › 💬`](https://discord.com/channels/1015931589865246730/1101481504141492254/1101828909500211221)

**Pull request closed without merging**
